#!/usr/bin/env python

import sys
import src.sample

def main(input_file, output_file, n_results):
  samples = src.sample.get_samples(input_file, int(n_results))
  output_file_handle = open(output_file, 'r')
  for sample in samples:
    output_file_handle.write(string(samples))

main(sys.argv[1], sys.argv[2], sys.argv[3])


